name: Release Drafter

on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-draft:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        with:
          commitish: refs/heads/master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
